create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  user_number bigint generated by default as identity,
  username text not null,
  username_key text generated always as (lower(username)) stored,
  display_name text,
  note text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (char_length(username) between 3 and 32),
  constraint profiles_username_format check (username ~ '^[A-Za-z0-9_]+$')
);

alter table public.profiles add column if not exists user_number bigint generated by default as identity;

create unique index if not exists profiles_user_number_unique on public.profiles (user_number);

create unique index if not exists profiles_username_key_unique
on public.profiles (username_key);

with ordered_profiles as (
  select id,row_number() over(order by created_at asc,id asc) as number
  from public.profiles
)
update public.profiles as profiles
set user_number=ordered_profiles.number
from ordered_profiles
where profiles.id=ordered_profiles.id;

select setval(
 pg_get_serial_sequence('public.profiles','user_number'),
 greatest(coalesce((select max(user_number) from public.profiles),1),1),
 coalesce((select max(user_number) from public.profiles),0)>0
);

create table if not exists public.username_history (
  id bigint generated always as identity primary key,
  username_key text not null unique,
  username text not null,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  user_number bigint,
  username text not null,
  display_name text,
  avatar_url text,
  text text not null,
  type text not null default 'text',
  created_at timestamptz not null default now(),
  constraint messages_type_check check (type in ('text', 'sticker'))
);

alter table public.messages add column if not exists user_number bigint;

update public.messages as messages
set user_number=profiles.user_number
from public.profiles as profiles
where messages.user_id=profiles.id and messages.user_number is null;

create index if not exists messages_created_at_index
on public.messages (created_at desc);

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint friend_requests_users_check check (requester_id <> recipient_id),
  constraint friend_requests_status_check check (status in ('pending', 'accepted', 'declined'))
);

create index if not exists friend_requests_recipient_index
on public.friend_requests (recipient_id, status);

create index if not exists friend_requests_requester_index
on public.friend_requests (requester_id, status);

create unique index if not exists friend_requests_pending_unique
on public.friend_requests (
  least(requester_id, recipient_id),
  greatest(requester_id, recipient_id)
)
where status in ('pending', 'accepted');

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint friendships_users_check check (user_a <> user_b)
);

create unique index if not exists friendships_pair_unique
on public.friendships (
  least(user_a, user_b),
  greatest(user_a, user_b)
);

create index if not exists friendships_user_a_index
on public.friendships (user_a);

create index if not exists friendships_user_b_index
on public.friendships (user_b);

create or replace function public.update_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;

create trigger profiles_updated_at
before update on public.profiles
for each row
execute function public.update_updated_at();

drop trigger if exists friend_requests_updated_at on public.friend_requests;

create trigger friend_requests_updated_at
before update on public.friend_requests
for each row
execute function public.update_updated_at();

create or replace function public.save_username_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.username_history (
      username_key,
      username,
      profile_id
    )
    values (
      lower(new.username),
      new.username,
      new.id
    )
    on conflict (username_key) do nothing;
    return new;
  end if;

  if tg_op = 'UPDATE' and old.username_key <> new.username_key then
    insert into public.username_history (
      username_key,
      username,
      profile_id
    )
    values (
      old.username_key,
      old.username,
      old.id
    )
    on conflict (username_key) do nothing;

    insert into public.username_history (
      username_key,
      username,
      profile_id
    )
    values (
      new.username_key,
      new.username,
      new.id
    )
    on conflict (username_key) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_username_history on public.profiles;

create trigger profiles_username_history
after insert or update of username on public.profiles
for each row
execute function public.save_username_history();

create or replace function public.create_friendship_after_accept()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'accepted' and old.status <> 'accepted' then
    insert into public.friendships (
      user_a,
      user_b
    )
    values (
      new.requester_id,
      new.recipient_id
    )
    on conflict do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists friend_request_accept_friendship on public.friend_requests;

create trigger friend_request_accept_friendship
after update of status on public.friend_requests
for each row
execute function public.create_friendship_after_accept();

alter table public.profiles enable row level security;
alter table public.username_history enable row level security;
alter table public.messages enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select
on public.profiles
for select
to authenticated
using (true);

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists username_history_select on public.username_history;
create policy username_history_select
on public.username_history
for select
to authenticated
using (true);

drop policy if exists messages_select on public.messages;
create policy messages_select
on public.messages
for select
to authenticated
using (true);

drop policy if exists messages_insert on public.messages;
create policy messages_insert
on public.messages
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists friend_requests_select on public.friend_requests;
create policy friend_requests_select
on public.friend_requests
for select
to authenticated
using (
  requester_id = auth.uid()
  or recipient_id = auth.uid()
);

drop policy if exists friend_requests_insert on public.friend_requests;
create policy friend_requests_insert
on public.friend_requests
for insert
to authenticated
with check (requester_id = auth.uid());

drop policy if exists friend_requests_update on public.friend_requests;
create policy friend_requests_update
on public.friend_requests
for update
to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

drop policy if exists friendships_select on public.friendships;
create policy friendships_select
on public.friendships
for select
to authenticated
using (
  user_a = auth.uid()
  or user_b = auth.uid()
);

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.username_history to authenticated;
grant select, insert on public.messages to authenticated;
grant select, insert, update on public.friend_requests to authenticated;
grant select on public.friendships to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'friend_requests'
  ) then
    alter publication supabase_realtime add table public.friend_requests;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'profiles'
  ) then
    alter publication supabase_realtime add table public.profiles;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'friendships'
  ) then
    alter publication supabase_realtime add table public.friendships;
  end if;
end;
$$;


drop policy if exists messages_delete on public.messages;
create policy messages_delete
on public.messages
for delete
to authenticated
using (user_id = auth.uid());

grant delete on public.messages to authenticated;

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references public.profiles(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint groups_name_length check (char_length(name) between 2 and 48)
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id,user_id)
);

create index if not exists group_members_user_id_index
on public.group_members (user_id);

create table if not exists public.group_messages (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  user_number bigint,
  username text not null,
  display_name text,
  avatar_url text,
  text text not null,
  type text not null default 'text',
  created_at timestamptz not null default now(),
  constraint group_messages_type_check check (type in ('text','sticker'))
);

create index if not exists group_messages_group_created_at_index
on public.group_messages (group_id,created_at desc);

create schema if not exists private;

create or replace function private.user_group_ids()
returns setof uuid
language sql
security definer
set search_path = ''
stable
as $$
  select group_id
  from public.group_members
  where user_id=(select auth.uid())
$$;

revoke execute on function private.user_group_ids() from public;
grant usage on schema private to authenticated;
grant execute on function private.user_group_ids() to authenticated;

create or replace function public.add_group_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.group_members(group_id,user_id)
  values(new.id,new.owner_id)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists groups_add_owner on public.groups;

create trigger groups_add_owner
after insert on public.groups
for each row
execute function public.add_group_owner();

create or replace function public.delete_group(group_id_value uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_group_id uuid;
begin
  if not exists (
    select 1
    from public.groups
    where id=group_id_value
      and owner_id=(select auth.uid())
      and deleted_at is null
  ) then
    raise exception 'Group not found or you are not allowed to delete it.';
  end if;

  delete from public.group_messages where group_id=group_id_value;
  delete from public.group_members where group_id=group_id_value;

  update public.groups
  set deleted_at=now()
  where id=group_id_value
    and owner_id=(select auth.uid())
    and deleted_at is null
  returning id into deleted_group_id;

  return deleted_group_id is not null;
end;
$$;

revoke execute on function public.delete_group(uuid) from public;
revoke execute on function public.delete_group(uuid) from anon;
grant execute on function public.delete_group(uuid) to authenticated;

alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;

drop policy if exists groups_select on public.groups;
create policy groups_select
on public.groups
for select
to authenticated
using (
  owner_id=(select auth.uid())
  or id in (select private.user_group_ids())
);

drop policy if exists groups_insert on public.groups;
create policy groups_insert
on public.groups
for insert
to authenticated
with check (owner_id=(select auth.uid()));

drop policy if exists groups_update on public.groups;
create policy groups_update
on public.groups
for update
to authenticated
using (owner_id=(select auth.uid()))
with check (owner_id=(select auth.uid()));

drop policy if exists group_members_select on public.group_members;
create policy group_members_select
on public.group_members
for select
to authenticated
using (group_id in (select private.user_group_ids()));

drop policy if exists group_members_insert on public.group_members;
create policy group_members_insert
on public.group_members
for insert
to authenticated
with check (
  user_id=(select auth.uid())
  or group_id in (
    select id
    from public.groups
    where owner_id=(select auth.uid())
      and deleted_at is null
  )
);

drop policy if exists group_members_delete on public.group_members;
create policy group_members_delete
on public.group_members
for delete
to authenticated
using (
  user_id=(select auth.uid())
  or group_id in (
    select id
    from public.groups
    where owner_id=(select auth.uid())
      and deleted_at is null
  )
);

drop policy if exists group_messages_select on public.group_messages;
create policy group_messages_select
on public.group_messages
for select
to authenticated
using (group_id in (select private.user_group_ids()));

drop policy if exists group_messages_insert on public.group_messages;
create policy group_messages_insert
on public.group_messages
for insert
to authenticated
with check (
  user_id=(select auth.uid())
  and group_id in (select private.user_group_ids())
);

drop policy if exists group_messages_delete on public.group_messages;
create policy group_messages_delete
on public.group_messages
for delete
to authenticated
using (user_id=(select auth.uid()));

grant select,insert,update on public.groups to authenticated;
grant select,insert,delete on public.group_members to authenticated;
grant select,insert,delete on public.group_messages to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='groups'
  ) then
    alter publication supabase_realtime add table public.groups;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='group_members'
  ) then
    alter publication supabase_realtime add table public.group_members;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='group_messages'
  ) then
    alter publication supabase_realtime add table public.group_messages;
  end if;
end;
$$;

alter table public.group_messages replica identity full;
