plugins {
    id "com.android.application"
}

android {
    namespace "app.swgc.roomchats"
    compileSdk 35

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId "app.swgc.roomchats"
        minSdk 23
        targetSdk 35
        versionCode = project.providers.gradleProperty("appVersionCode").getOrElse("1").toInteger()
        versionName = project.providers.gradleProperty("appVersionName").getOrElse("1.0.0").toString()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
