plugins {
    id "com.android.application"
}

android {
    namespace "app.swgc.roomchats"
    compileSdk 35

    defaultConfig {
        applicationId "app.swgc.roomchats"
        minSdk 23
        targetSdk 35
        versionCode (project.findProperty("appVersionCode") ?: "1").toInteger()
        versionName (project.findProperty("appVersionName") ?: "1.0.0").toString()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
